#ifndef _language_
#define _language_
#include "settings.h"
 

#ifdef S65_LANG_SK
/*
	#define ZADAVANIE_CENY_2_DESATINNE_MIESTA
	#define ZNAK_MENY
	#define EUR
*/
	#define TXT_HODINY				"Hodiny"
	#define TXT_CENA			  	"Cena paliva"
	#define TXT_0Kc				  	"0Kc"
	#define TXT_SERVIS_Z	  	"Servis zostava"
	#define TXT_SERVIS_I	  	"Servis interval"
	#define TXT_FARBY			  	"Farby"
	#define TXT_TEXT			  	"Text"
	#define TXT_PODKLAD		  	"Podklad"
	#define TXT_PODSVIETENIE 	"Podsvietenie"
	#define TXT_MIN				 		"Min"
	#define TXT_MAX				 		"Max"
	#define TXT_VALCE					"Pocet valcov"
	#define TXT_VSTREKOVAC		"Vstrekovac"
	#define TXT_KOLESA				"Pneumatiky"
	#define TXT_CIDLO					"Cidlo rychlosti"
	#define TXT_NAKLON				"Naklon"
	#define TXT_CAS				  	" Cas:"
	#define TXT_ZRYCHLENIE  	"Zrychlenie z 0 na"
	#define TXT_POCETMENUBC		"Pocet BC menu"
	#define TXT_MAX_DOBA			"Max. doba jazdy"
	#define TXT_OTACKY				"Ot./min"
	#define TXT_DLZKA_VSTREKU	"Dlzka vstreku"
	#define TXT_OBR_ZRYCHLENIE "Obr.zrychlenie"
	#define TXT_OBR_PRETAZENIE "Obr.pretazenie"
	#define TXT_OBR_MOTOR 		"Obr.motor"
	#define TXT_OBR_STOPKY 		"Obr.stopky"
	#define TXT_OBR_DEVELOP		"Obr.develop"
	#define TXT_STOPKY		 		"Stopky"
	#define TXT_OFF						"Vyp"
	#define TXT_ON						"Zap"
	#define TXT_INT						"INT"
	#define TXT_LAP						"LAP"
	#define TXT_J							"J"
	#define TXT_C							"C"
	#define TXT_WWW2					"    www.calibra.cz"
	#define TXT_WWW						"   www.ppf.borec.cz"
	#define TXT_H							"h"
	#define TXT_M							"m"
	#define TXT_S							"s"
	#define TXT_TOT						"Tot"
	#define TXT_V							"V"
	#define TXT_OUT						"Out"
	#define TXT_WELCOMETEXT		"Uvitaci txt"
	#define TXT_NAST_NADRZE		"Nast.nadrze"
	#define TXT_400M					"Sprint     na"
	#define TXT_OBR_SPRINT		"Obr.sprint"
	#define TXT_RYCHLOST			"Rychlost:"
	#define TXT_TEPLOTA_MOTORU "Teplota oleja "
	#define TXT_LAMBDA	 			"Lambda"
	#define TXT_LAMBDA_M 			"Lambda mereni"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"



	#define TXT_KMH						"Km/h"
	#define TXT_l100Km				"l/100Km"
	#define TXT_KM						"Km"
	#define TXT_KMHR					"Km"
	#define TXT_KMSR					"/h"
	#define TXT_L100KMHR			"l/"
	#define TXT_L100KMSR			"100"
 	#define TXT_L		"l"

#endif


#ifdef S65_LANG_CZ
/*
	#define ZADAVANIE_CENY_1_DESATINNE_MIESTO
	#define TXT_MENA					"0Kc"
	#define TXT_MENAHR				"Kc"
	#define TXT_MENASR				"  "
*/
	#define TXT_HODINY				"Hodiny"
	#define TXT_CENA			  	"Cena paliva"
	#define TXT_SERVIS_Z	  	"Servis zustava"
	#define TXT_SERVIS_I	  	"Servis interval"
	#define TXT_FARBY			 	 	"Barvy"
	#define TXT_TEXT			  	"Text"
	#define TXT_PODKLAD		  	"Podklad"
	#define TXT_PODSVIETENIE 	"Podsviceni"
	#define TXT_MIN				 		"Min"
	#define TXT_MAX				 		"Max"
	#define TXT_VALCE					"Pocet valcu"
	#define TXT_VSTREKOVAC		"Vstrikovac"
	#define TXT_KOLESA				"Pneumatiky"
	#define TXT_CIDLO					"Cidlo rychlosti"
	#define TXT_NAKLON				"Naklon"
	#define TXT_CAS				  	" Cas:"
	#define TXT_ZRYCHLENIE  	"Zrychleni z 0 na"
	#define TXT_POCETMENUBC		"Pocet BC menu"
	#define TXT_MAX_DOBA			"Max. doba jizdy"
	#define TXT_OTACKY				"Ot./min"
	#define TXT_DLZKA_VSTREKU	"Delka vstriku"
	#define TXT_OBR_ZRYCHLENIE "Obr.zrychleni"
	#define TXT_OBR_PRETAZENIE "Obr.pretizeni"
	#define TXT_OBR_MOTOR 		"Obr.motor"
	#define TXT_OBR_STOPKY 		"Obr.stopky"
	#define TXT_OBR_DEVELOP		"Obr.develop"
	#define TXT_STOPKY		 		"Stopky"
	#define TXT_OFF						"Vyp"
	#define TXT_ON						"Zap"
	#define TXT_INT						"INT"
	#define TXT_LAP						"LAP"
	#define TXT_J							"J"
	#define TXT_C							"C"
	#define TXT_WWW						"   www.ppf.borec.cz"
	#define TXT_WWW2					"    www.calibra.cz"
	#define TXT_H							"h"
	#define TXT_M							"m"
	#define TXT_S							"s"
	#define TXT_TOT						"Tot"
	#define TXT_V							"V"
	#define TXT_OUT						"Out"
	#define TXT_WELCOMETEXT		"Uvitaci txt"
	#define TXT_NAST_NADRZE		"Nast.nadrze"
	#define TXT_400M					"Sprint     na"
	#define TXT_OBR_SPRINT		"Obr.sprint"
	#define TXT_RYCHLOST			"Rychlost:"
	#define TXT_TEPLOTA_MOTORU "Teplota oleje "
	#define TXT_LAMBDA	 			"Lambda"
	#define TXT_LAMBDA_M 			"Lambda mereni"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"


	#define TXT_KMH						"Km/h"
	#define TXT_l100Km				"l/100Km"
	#define TXT_KM						"Km"
	#define TXT_KMHR					"Km"
	#define TXT_KMSR					"/h"
	#define TXT_L100KMHR			"l/"
	#define TXT_L100KMSR			"100"
 	#define TXT_L		"l"

#endif


#ifdef S65_LANG_EN
/*
	#define ZADAVANIE_CENY_2_DESATINNE_MIESTA
	#define ZNAK_MENY
	#define EUR
*/
	#define TXT_HODINY				"Clock"
	#define TXT_CENA			  	"Fuel price"
  #define TXT_0Kc				  	"0Kc"
	#define TXT_SERVIS_Z	  	"Service left"
	#define TXT_SERVIS_I	  	"Service int."
	#define TXT_FARBY			  	"Colours"
	#define TXT_TEXT			  	"Text"
	#define TXT_PODKLAD		  	"Bckgrnd"
	#define TXT_PODSVIETENIE "Illumination"
	#define TXT_MIN				 		"Min"
	#define TXT_MAX				 		"Max"
	#define TXT_VALCE					"Nr. of cylinders"
	#define TXT_VSTREKOVAC		"Injector"
	#define TXT_KOLESA				"Tyres"
	#define TXT_CIDLO					"Speed sensor"
	#define TXT_NAKLON				"Heeling"
	#define TXT_CAS				  	"Time:"
	#define TXT_ZRYCHLENIE  	"Acceleration 0 to"
	#define TXT_POCETMENUBC		"Nr. of BC screen"	
	#define TXT_MAX_DOBA			"Safety break"
	#define TXT_OTACKY				"RPM"
	#define TXT_DLZKA_VSTREKU	"Injector time"
	#define TXT_OBR_ZRYCHLENIE "Scr.acceleration"
	#define TXT_OBR_PRETAZENIE "Scr. G"
	#define TXT_OBR_MOTOR 		"Scr.engine"
	#define TXT_OBR_STOPKY 		"Scr.stop watch"
	#define TXT_OBR_DEVELOP		"Scr.develop"
	#define TXT_STOPKY		 		"Stop watch"
	#define TXT_INT						"INT"
	#define TXT_LAP						"LAP"
	#define TXT_OFF						"OFF"
	#define TXT_ON						" ON"
	#define TXT_J							"A"
	#define TXT_C							"O"
	#define TXT_WWW						"   www.ppf.borec.cz"
	#define TXT_WWW2					" "
	#define TXT_H							"h"
	#define TXT_M							"m"
	#define TXT_S							"s"
	#define TXT_TOT						"Tot"
	#define TXT_V							"V"
	#define TXT_OUT						"Out"
	#define TXT_WELCOMETEXT		"Welcome txt"
	#define TXT_NAST_NADRZE		"Fuel level"
	#define TXT_400M					"Measuring time"
	#define TXT_OBR_SPRINT		"Scr. sprint"
	#define TXT_RYCHLOST			"Speed:"
	#define TXT_TEPLOTA_MOTORU "Oil temp.     "
	#define TXT_LAMBDA	 			"Lambda"
	#define TXT_LAMBDA_M 			"Lambda measurement"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"


	#define TXT_KMH						"Km/h"
	#define TXT_l100Km				"l/100Km"
	#define TXT_KM						"Km"
	#define TXT_KMHR					"Km"
	#define TXT_KMSR					"/h"
	#define TXT_L100KMHR			"l/"
	#define TXT_L100KMSR			"100"
 	#define TXT_L		"l"

#endif


#ifdef S65_LANG_BR
/*
		Brazilsk· portugalötina

	#define ZADAVANIE_CENY_2_DESATINNE_MIESTA
	#define ZNAK_MENY
	#define USD
*/
 	#define TXT_HODINY   "Relogio"
  #define TXT_CENA   "Preco Combust."
  #define TXT_SERVIS_Z   "Proxima revisao"
  #define TXT_SERVIS_I   "Mudanca de oleo"
  #define TXT_FARBY   "Cores"
  #define TXT_TEXT   "Texto"
  #define TXT_PODKLAD   " Fundo"
  #define TXT_PODSVIETENIE   "Iluminacao"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "ÂÊ de cilindros"
  #define TXT_VSTREKOVAC   "Injetores"
  #define TXT_KOLESA   "Pneus"
  #define TXT_CIDLO   "Sensor velocidade"
  #define TXT_NAKLON   "Inclinacao"
  #define TXT_POCETMENUBC   "ÂÊ da tela do BC"
  #define TXT_MAX_DOBA   "Parada de segur."
  #define TXT_OBR_ZRYCHLENIE    "Tela de Aceleracao"
  #define TXT_OBR_PRETAZENIE    "Forca G"
  #define TXT_OBR_MOTOR    "Tela Motor"
//  #define TXT_OBR_SPRINT   "Quatro de milha"
  #define TXT_OBR_SPRINT   "D250"
  #define TXT_OFF   "Des"
  #define TXT_ON   "Lig"
  #define TXT_WELCOMETEXT   "Bem vindo"
  #define TXT_NAST_NADRZE   "Nivel Comb."
  #define TXT_OUT   "Ext"
  #define TXT_J   "A"
  #define TXT_C   "O"
  #define TXT_CAS   "Tempo"
  #define TXT_ZRYCHLENIE     "Aceleracao 0 a"
  #define TXT_OTACKY   "RPM"
  #define TXT_DLZKA_VSTREKU   "Tempo de pulso"
//  #define TXT_400M   "Tempo distancia"
  #define TXT_400M   "D250"
  #define TXT_RYCHLOST   "Velocidade"
  #define TXT_TOT   "Tot"
  #define TXT_TEPLOTA_MOTORU   "Temp. do oleo"
	#define TXT_OBR_STOPKY 		"Tela cronometro"
	#define TXT_STOPKY		 		"Cronometro"
	#define TXT_INT						"INT"
	#define TXT_LAP						"LAP"
  #define TXT_OBR_DEVELOP   "Tela diagnostico"
	#define TXT_LAMBDA	 			"Lambda"
	#define TXT_LAMBDA_M 			"Medicao Lambda"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"





  #define TXT_WWW2   ""
  #define TXT_KMH   "Km/h"
  #define TXT_l100Km   "l/100Km"
  #define TXT_KM   "Km"
  #define TXT_KMHR   "Km"
  #define TXT_KMSR   "/h"
  #define TXT_L100KMHR   "l/"
  #define TXT_L100KMSR   "100"
  #define TXT_WWW   "   www.ppf.borec.cz"
  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
  #define TXT_L   "l"
#endif


#ifdef S65_LANG_BR1
/*
		Brazilsk· portugalötina

	#define ZADAVANIE_CENY_2_DESATINNE_MIESTA
	#define ZNAK_MENY
	#define USD
*/
  #define TXT_HODINY   "Relogio"
  #define TXT_CENA   "Preco Combust."
  #define TXT_SERVIS_Z   "Proxima revisao"
  #define TXT_SERVIS_I   "Trocas de oleo"
  #define TXT_FARBY   "Cores"
  #define TXT_TEXT   "TXT"
  #define TXT_PODKLAD   "Fundo"
  #define TXT_PODSVIETENIE   "Iluminacao"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "Nr. de cilindros"
  #define TXT_VSTREKOVAC   "Injetores"
  #define TXT_KOLESA   "Pneus"
  #define TXT_CIDLO   "Sensor velocidade"
  #define TXT_NAKLON   "Inclinacao"
  #define TXT_POCETMENUBC   "ÂÊ da tela do BC"
  #define TXT_MAX_DOBA   "Pausa Seguranca"
  #define TXT_OBR_ZRYCHLENIE    "Tela de Aceleracao"
  #define TXT_OBR_PRETAZENIE    "Forca G"
  #define TXT_OBR_MOTOR    "Tela Motor"
  #define TXT_OBR_SPRINT   "Tela Arrancada"
  #define TXT_OFF   "Des"
  #define TXT_ON   "Lig"
  #define TXT_WELCOMETEXT   "Boas Vindas"
  #define TXT_NAST_NADRZE   "Nivel Comb."
  #define TXT_OUT   "Ext"
  #define TXT_J   "A"
  #define TXT_C   "O"
  #define TXT_CAS   "Tempo"
  #define TXT_ZRYCHLENIE     "Aceleracao 0 a"
  #define TXT_OTACKY   "RPM"
  #define TXT_DLZKA_VSTREKU   "Tempo Injetor"
  #define TXT_400M   "Tempo distancia"
  #define TXT_RYCHLOST   "Velocidade"
  #define TXT_TOT   "Tot"
  #define TXT_TEPLOTA_MOTORU   "Temp. do oleo"
  #define TXT_INT   "INT"
  #define TXT_LAP   "LAP"
  #define TXT_STOPKY   "Cronometro"
  #define TXT_OBR_STOPKY   "Tela cronometro"
  #define TXT_OBR_DEVELOP   "Tela diagnostico"
  #define TXT_LAMBDA   "Lambda"
  #define TXT_LAMBDA_M   "Lambda medicao"
  #define TXT_BUFFER   "BFR"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"





  #define TXT_WWW2   ""
  #define TXT_KMH   "Km/h"
  #define TXT_l100Km   "l/100Km"
  #define TXT_KM   "Km"
  #define TXT_KMHR   "Km"
  #define TXT_KMSR   "/h"
  #define TXT_L100KMHR   "l/"
  #define TXT_L100KMSR   "100"
  #define TXT_WWW   "   www.ppf.borec.cz"
  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
  #define TXT_L   "l"
#endif


#ifdef S65_LANG_UK
/*
	#define ZADAVANIE_CENY_2_DESATINNE_MIESTA
	#define ZNAK_MENY
	#define GBP
*/
	#define MPH
	#define LCD_MIRROR
	#define	H12

	#define TXT_HODINY				"Clock"
	#define TXT_CENA			  	"Fuel price"
  #define TXT_0Kc				  	"0Kc"
	#define TXT_SERVIS_Z	  	"Service left"
	#define TXT_SERVIS_I	  	"Service int."
	#define TXT_FARBY			  	"Colours"
	#define TXT_TEXT			  	"Text"
	#define TXT_PODKLAD		  	"Bckgrnd"
	#define TXT_PODSVIETENIE "Illumination"
	#define TXT_MIN				 		"Min"
	#define TXT_MAX				 		"Max"
	#define TXT_VALCE					"Nr. of cylinders"
	#define TXT_VSTREKOVAC		"Injector"
	#define TXT_KOLESA				"Tyres"
	#define TXT_CIDLO					"Speed sensor"
	#define TXT_NAKLON				"Heeling"
	#define TXT_CAS				  	"Time:"
	#define TXT_ZRYCHLENIE  	"Acceleration 0 to"
	#define TXT_POCETMENUBC		"Nr. of BC screen"	
	#define TXT_MAX_DOBA			"Safety break"
	#define TXT_OTACKY				"RPM"
	#define TXT_DLZKA_VSTREKU	"Injector time"
	#define TXT_OBR_ZRYCHLENIE "Scr.acceleration"
	#define TXT_OBR_PRETAZENIE "Scr. G"
	#define TXT_OBR_MOTOR 		"Scr.engine"
	#define TXT_OBR_STOPKY 		"Scr.stop watch"
	#define TXT_OBR_DEVELOP		"Scr.develop"
	#define TXT_STOPKY		 		"Stop watch"
	#define TXT_INT						"INT"
	#define TXT_LAP						"LAP"
	#define TXT_OFF						"OFF"
	#define TXT_ON						" ON"
	#define TXT_J							"A"
	#define TXT_C							"O"
	#define TXT_WWW						"   www.ppf.borec.cz"
	#define TXT_WWW2					" "
	#define TXT_H							"h"
	#define TXT_M							"m"
	#define TXT_S							"s"
	#define TXT_TOT						"Tot"
	#define TXT_V							"V"
	#define TXT_OUT						"Out"
	#define TXT_WELCOMETEXT		"Welcome txt"
	#define TXT_NAST_NADRZE		"Fuel level"
	#define TXT_400M					"Measuring time"
	#define TXT_OBR_SPRINT		"Scr. sprint"
	#define TXT_RYCHLOST			"Speed:"
	#define TXT_TEPLOTA_MOTORU "Oil temp.     "
	#define TXT_LAMBDA	 			"Lambda"
	#define TXT_LAMBDA_M 			"Lambda measurement"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"


	#define TXT_KMH						" mph"
	#define TXT_l100Km				"    mpg"
	#define TXT_KM						"m"
	#define TXT_KMHR					""
	#define TXT_KMSR					"mph"
	#define TXT_L100KMHR			""
	#define TXT_L100KMSR			"mpg"
 	#define TXT_L							"l"

#endif

#ifdef S65_LANG_NOR
/*
	#define ZADAVANIE_CENY_1_DESATINNE_MIESTO
	#define TXT_MENA					"NOK"
	#define TXT_MENAHR				"NO"
	#define TXT_MENASR				"K "
*/
	#define TXT_HODINY				"Clock"
	#define TXT_CENA			  	"Fuel price"
  #define TXT_0Kc				  	"0Kc"
	#define TXT_SERVIS_Z	  	"Service left"
	#define TXT_SERVIS_I	  	"Service int."
	#define TXT_FARBY			  	"Colours"
	#define TXT_TEXT			  	"Text"
	#define TXT_PODKLAD		  	"Bckgrnd"
	#define TXT_PODSVIETENIE "Illumination"
	#define TXT_MIN				 		"Min"
	#define TXT_MAX				 		"Max"
	#define TXT_VALCE					"Nr. of cylinders"
	#define TXT_VSTREKOVAC		"Injector"
	#define TXT_KOLESA				"Tyres"
	#define TXT_CIDLO					"Speed sensor"
	#define TXT_NAKLON				"Heeling"
	#define TXT_CAS				  	"Time:"
	#define TXT_ZRYCHLENIE  	"Acceleration 0 to"
	#define TXT_POCETMENUBC		"Nr. of BC screen"	
	#define TXT_MAX_DOBA			"Safety break"
	#define TXT_OTACKY				"RPM"
	#define TXT_DLZKA_VSTREKU	"Injector time"
	#define TXT_OBR_ZRYCHLENIE "Scr.acceleration"
	#define TXT_OBR_PRETAZENIE "Scr. G"
	#define TXT_OBR_MOTOR 		"Scr.engine"
	#define TXT_OFF						"OFF"
	#define TXT_ON						" ON"
	#define TXT_J							"A"
	#define TXT_C							"O"
	#define TXT_WWW						"   www.ppf.borec.cz"
	#define TXT_WWW2					" "
	#define TXT_H							"h"
	#define TXT_M							"m"
	#define TXT_S							"s"
	#define TXT_TOT						"Tot"
	#define TXT_V							"V"
	#define TXT_OUT						"Out"
	#define TXT_WELCOMETEXT		"Welcome txt"
	#define TXT_NAST_NADRZE		"Fuel level"
	#define TXT_400M					"Measuring time"
	#define TXT_OBR_SPRINT		"Scr. sprint"
	#define TXT_RYCHLOST			"Speed:"
	#define TXT_TEPLOTA_MOTORU "Oil temp.     "

	#define TXT_KMH						"Km/h"
	#define TXT_l100Km				"l/100Km"
	#define TXT_KM						"Km"
	#define TXT_KMHR					"Km"
	#define TXT_KMSR					"/h"
	#define TXT_L100KMHR			"l/"
	#define TXT_L100KMSR			"100"
 	#define TXT_L		"l"

#endif


#ifdef S65_LANG_PLN

/*
	#define ZADAVANIE_CENY_2_DESATINNE_MIESTA
//	#define ZADAVANIE_CENY_1_DESATINNE_MIESTO
//	#define ZNAK_MENY
//	#define EUR
	#define TXT_MENA					"PLN"
	#define TXT_MENAHR				"PL"
	#define TXT_MENASR				"N "
*/		

  #define TXT_HODINY				"Zegar"
  #define TXT_CENA  	   	 	"Cena paliwa"
  #define TXT_SERVIS_Z    	"Serwis za" //- pozosta≥o do serwisu
  #define TXT_SERVIS_I    	"Wymiana oleju" //- ?? intake? what that means?
  #define TXT_FARBY       	"Kolory"
  #define TXT_TEXT        	"Tekst"
  #define TXT_PODKLAD     	"   Tla"
  #define TXT_PODSVIETENIE	"Podswietlenie"
  #define TXT_MIN           "Min"
  #define TXT_MAX           "Max"
  #define TXT_VALCE         "Ilosc cylindrow"
  #define TXT_VSTREKOVAC    "Wtryskiwacz"
  #define TXT_KOLESA        "Opony"
  #define TXT_CIDLO         "Czujnik predkosci" 
  #define TXT_NAKLON        "Przechyl"
  #define TXT_CAS           "Czas:"
  #define TXT_ZRYCHLENIE    "Przysp.   od 0 do"
  #define TXT_POCETMENUBC   "Nr. ekranu BC"     
  #define TXT_MAX_DOBA      "Przerwa bezp."  // dal brzdu Przerwa bezpieczenstwa
  #define TXT_OTACKY        "RPM"
  #define TXT_DLZKA_VSTREKU "Czas wtrysku"  
  #define TXT_OBR_ZRYCHLENIE "Ek. przyspieszenia"
  #define TXT_OBR_PRETAZENIE "Ek. przeciazen"
  #define TXT_OBR_MOTOR      "Ek. silnika" 
  #define TXT_OFF           "Wyl"// - wy≥πczony
  #define TXT_ON            "Zal"// - za≥πczony
  #define TXT_J             "A" // aktualny przejazd
  #define TXT_C             "O" // dane ogÛlne
	#define TXT_WWW						"   www.ppf.borec.cz"
	#define TXT_WWW2					" www.mickey-garage.pl"
	#define TXT_H							"h"
	#define TXT_M							"m"
	#define TXT_S							"s"
	#define TXT_TOT						"Cal" //ca≥oúci
	#define TXT_V							"V"
	#define TXT_OUT						"Zew"
	#define TXT_WELCOMETEXT		"Pozdrawia"
	#define TXT_NAST_NADRZE		"Poziom pal."
	#define TXT_400M					"Czas      na"
	#define TXT_OBR_SPRINT		"Ek. sprint"
	#define TXT_RYCHLOST			"Predkosc:"

	#define TXT_KMH						"Km/h"
	#define TXT_l100Km				"l/100Km"
	#define TXT_KM						"Km"
	#define TXT_KMHR					"Km"
	#define TXT_KMSR					"/h"
	#define TXT_L100KMHR			"l/"
	#define TXT_L100KMSR			"100"
 	#define TXT_L		"l"

#endif


#ifdef S65_LANG_IT

/*
	#define ZADAVANIE_CENY_2_DESATINNE_MIESTA
	#define ZNAK_MENY
	#define EUR
	*/

  #define TXT_HODINY   			"Orologio"
  #define TXT_CENA   				"Costo benzina"
  #define TXT_SERVIS_Z   		"Km al tagliando"
  #define TXT_SERVIS_I   		"Intervallo tagl"
  #define TXT_FARBY   			"Colori"
  #define TXT_TEXT   				"Text"
  #define TXT_PODKLAD   		"Sfondo"
  #define TXT_PODSVIETENIE  "Illuminazione"
  #define TXT_MIN   				"Min"
  #define TXT_MAX   				"Max"
  #define TXT_VALCE   			"Nr cilindri"
  #define TXT_VSTREKOVAC   	"Iniettori"
  #define TXT_KOLESA   			"Pneumatici"
  #define TXT_CIDLO   			"Sensore velocita"
  #define TXT_NAKLON   			"Reset giroscopio"
  #define TXT_POCETMENUBC   "Nr schermate BC"
  #define TXT_MAX_DOBA   		"Pausa guida"
  #define TXT_OBR_ZRYCHLENIE "Scr acceleraz"
  #define TXT_OBR_PRETAZENIE "Scr acceleraz G"
  #define TXT_OBR_MOTOR    	"Scr motore"
  #define TXT_OBR_SPRINT   	"Scr scatto"
  #define TXT_OFF   				"OFF"
  #define TXT_ON   					" ON"
  #define TXT_WELCOMETEXT   "Txt accens"
  #define TXT_NAST_NADRZE   "Liv benzina"
  #define TXT_OUT   				"Est"
  #define TXT_J   					"A"
  #define TXT_C   					"M"
  #define TXT_CAS   				"Tempo"
  #define TXT_ZRYCHLENIE    "Acceleraz     0 -"
  #define TXT_OTACKY   			"RPM"
  #define TXT_DLZKA_VSTREKU "Tempo iniezione"
  #define TXT_400M   				"Tempo misurato "
  #define TXT_RYCHLOST   		"Velocita"
	#define TXT_TEPLOTA_MOTORU "Olio temp.    "
	#define TXT_LAMBDA	 			"Lambda"
	#define TXT_LAMBDA_M 			"Lambda misurato"
	#define TXT_STOPKY		 		"Cronometro"
	#define TXT_INT						"INT"
	#define TXT_LAP						"LAP"
	#define TXT_OBR_STOPKY 		"Scr cronometro"
	#define TXT_OBR_DEVELOP		"Scr develop"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"


  #define TXT_WWW2   				""
  #define TXT_KMH   				"Km/h"
  #define TXT_l100Km   			"l/100Km"
  #define TXT_KM   					"Km"
  #define TXT_KMHR   				"Km"
  #define TXT_KMSR   				"/h"
  #define TXT_L100KMHR   		"l/"
  #define TXT_L100KMSR   		"100"
  #define TXT_WWW   				"   www.ppf.borec.cz"
  #define TXT_H   					"h"
  #define TXT_M   					"m"
  #define TXT_S   					"s"
  #define TXT_TOT   				"Tot"
  #define TXT_V   					"V"
 	#define TXT_L		"l"

#endif



#ifdef S65_LANG_DE

/*
	#define ZADAVANIE_CENY_2_DESATINNE_MIESTA
	#define ZNAK_MENY
	#define EUR
*/

   #define TXT_HODINY   		"Uhr"
  #define TXT_CENA   				"Benzinpreis"
  #define TXT_SERVIS_Z   		"Kundend. fÜllig"
  #define TXT_SERVIS_I   		"Kundend. Inter."
  #define TXT_FARBY   			"Farben"
  #define TXT_TEXT   				"Text"
  #define TXT_PODKLAD   		"Hinter"
  #define TXT_PODSVIETENIE 	"Beleuchtung"
  #define TXT_MIN   				"Min"
  #define TXT_MAX   				"Max"
  #define TXT_VALCE   			"Anz. Zylinder"
  #define TXT_VSTREKOVAC  	"Einspritzung"
  #define TXT_KOLESA   			"Reifen"
  #define TXT_CIDLO   			"Geschw. Sensor"
  #define TXT_NAKLON   			"Neigung"
  #define TXT_POCETMENUBC 	"Nr. der BC Anzeige"
  #define TXT_MAX_DOBA   		"Sicherheitspause"
  #define TXT_OBR_ZRYCHLENIE "Anz.Beschleunigung"
  #define TXT_OBR_PRETAZENIE "Anz. G-Belastung"
  #define TXT_OBR_MOTOR    	"Anzeige Motor"
  #define TXT_OBR_SPRINT   	"Anzeige Sprint"
  #define TXT_OFF   				"Aus"
  #define TXT_ON   					" An"
  #define TXT_WELCOMETEXT   "Verabschie."
  #define TXT_NAST_NADRZE   "Benzinstand"
  #define TXT_OUT   				"AuÖ"
  #define TXT_J   					"F"
  #define TXT_C   					"E"
  #define TXT_CAS   				"Zeit:"
  #define TXT_ZRYCHLENIE    "Beschl. von 0 auf"
  #define TXT_OTACKY   			"Drehzahl"
  #define TXT_DLZKA_VSTREKU "Einspritz-Zeit"
  #define TXT_400M   				"Messstrecke"
  #define TXT_RYCHLOST   		"Geschw.:"
  #define TXT_TOT   				"Ins"
  #define TXT_TEPLOTA_MOTORU   "Motoroltemp."
	#define TXT_OBR_DEVELOP		"Scr.develop"
	#define TXT_STOPKY		 		"Stoppuhr"
	#define TXT_INT						"INT"
	#define TXT_LAP						"LAP"
	#define TXT_OBR_STOPKY 		"Scr.stoppuhr"
	#define TXT_LAMBDA	 			"Lambda"
	#define TXT_LAMBDA_M 			"Lambda messung"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"



  #define TXT_WWW2   				""
  #define TXT_KMH   				"Km/h"
  #define TXT_l100Km   			"l/100Km"
  #define TXT_KM   					"Km"
  #define TXT_KMHR   				"Km"
  #define TXT_KMSR   				"/h"
  #define TXT_L100KMHR   		"l/"
  #define TXT_L100KMSR   		"100"
  #define TXT_WWW   				"   www.ppf.borec.cz"
  #define TXT_H   					"h"
  #define TXT_M   					"m"
  #define TXT_S   					"s"
  #define TXT_V   					"V"
 	#define TXT_L		"l"

#endif

#ifdef S65_LANG_HU
/*
	#define ZADAVANIE_CENY_0_DESATINNYCH_MIEST
	#define TXT_MENA					"HUF"
//	#define TXT_MENAHR				" "
//	#define TXT_MENASR				"  "
//	#define ZNAK_MENY
//	#define EUR
*/
   #define TXT_HODINY   "Ora"
  #define TXT_CENA   "Uzemanyag ar"
  #define TXT_SERVIS_Z   "Hatralevo KM"
  #define TXT_SERVIS_I   "Szerviz"
  #define TXT_FARBY   "Szinek"
  #define TXT_TEXT   "Betu"
  #define TXT_PODKLAD   "Hatter"
  #define TXT_PODSVIETENIE   "Fenyero"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "Hengerek szama"
  #define TXT_VSTREKOVAC   "Injektor"
  #define TXT_KOLESA   "Gumiabroncs"
  #define TXT_CIDLO   "Sebesseg szenzor"
  #define TXT_NAKLON   "Reset - Nullazas"
  #define TXT_POCETMENUBC   "Kijelzo Mod"
  #define TXT_MAX_DOBA   "Piheno"
  #define TXT_OBR_ZRYCHLENIE    "Gyorsulas kijelzes"
  #define TXT_OBR_PRETAZENIE    "G-ero kijelzes"
  #define TXT_OBR_MOTOR    "Motor kijelzes"
  #define TXT_OBR_SPRINT   "Stopper"
  #define TXT_OFF   " KI"
  #define TXT_ON   " BE"
  #define TXT_WELCOMETEXT   "Udvozlo sz."
  #define TXT_NAST_NADRZE   "Tank szint"
  #define TXT_OUT   "Kin"
  #define TXT_J   "P"
  #define TXT_C   "A"
  #define TXT_CAS   "Ido"
  #define TXT_ZRYCHLENIE     "Gyorsulas     0 -"
  #define TXT_OTACKY   "Fordulat"
  #define TXT_DLZKA_VSTREKU   "Injektor Ido"
  #define TXT_400M   "Mert Ido"
  #define TXT_RYCHLOST   "Sebesseg"
  #define TXT_TOT   "Tot"

  #define TXT_WWW2   ""
  #define TXT_KMH   "Km/h"
  #define TXT_l100Km   "l/100Km"
  #define TXT_KM   "Km"
  #define TXT_KMHR   "Km"
  #define TXT_KMSR   "/h"
  #define TXT_L100KMHR   "l/"
  #define TXT_L100KMSR   "100"
  #define TXT_WWW   "   www.ppf.borec.cz"
  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
 	#define TXT_L		"l"


#endif


#ifdef S65_LANG_RO

  #define TXT_HODINY   "Ceas"
  #define TXT_CENA   "Pret combust."
  #define TXT_SERVIS_Z   "Pina la servis"
  #define TXT_SERVIS_I   "Servis int."
  #define TXT_FARBY   "Culori"
  #define TXT_TEXT   "Text"
  #define TXT_PODKLAD   "Fundal"
  #define TXT_PODSVIETENIE   "Iluminatie"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "Nr. cilindri"
  #define TXT_VSTREKOVAC   "Injectori"
  #define TXT_KOLESA   "Anvelope"
  #define TXT_CIDLO   "Sensor viteza"
  #define TXT_NAKLON   "Bandare setari"
  #define TXT_POCETMENUBC   "Nr. Ecran"
  #define TXT_MAX_DOBA   "Pauza odihna"
  #define TXT_OBR_ZRYCHLENIE    "Ecran accelerare"
  #define TXT_OBR_PRETAZENIE    "Ecran G"
  #define TXT_OBR_MOTOR    "Ecran motor"
  #define TXT_OBR_SPRINT   "Ecran sprint"
  #define TXT_OFF   "OFF"
  #define TXT_ON   " ON"
  #define TXT_WELCOMETEXT   "Txt intimp."
  #define TXT_NAST_NADRZE   "Niv Combust"
  #define TXT_OUT   "Tmp"
  #define TXT_J   "A"
  #define TXT_C   "G"
  #define TXT_CAS   "Timp:"
  #define TXT_ZRYCHLENIE     "Accelerare 0 la"
  #define TXT_OTACKY   "RPM"
  #define TXT_DLZKA_VSTREKU   "Timp injector"
  #define TXT_400M   "Sprint"
  #define TXT_RYCHLOST   "Viteza:"
  #define TXT_TOT   "Tot"
	#define TXT_TEPLOTA_MOTORU "Temp. ulei    "


  #define TXT_WWW2   ""
  #define TXT_KMH   "Km/h"
  #define TXT_l100Km   "l/100Km"
  #define TXT_KM   "Km"
  #define TXT_KMHR   "Km"
  #define TXT_KMSR   "/h"
  #define TXT_L100KMHR   "l/"
  #define TXT_L100KMSR   "100"
  #define TXT_WWW   "   www.ppf.borec.cz"
  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
 	#define TXT_L		"l"



#endif


#ifdef S65_LANG_RU

	#define AZBUKA

  #define TXT_HODINY   "∑¬“⁄"
  #define TXT_CENA   "∂«Œ¬ ”œ–Ã ƒ¬"
  #define TXT_SERVIS_Z   "±«—ƒ “ ÿ«—«…"
  #define TXT_SERVIS_I   "±«—ƒ “  Œ”«—ƒ¬Ã"
  #define TXT_FARBY   "∂ƒ«”"
  #define TXT_TEXT   "≤«À“”"
  #define TXT_PODKLAD   "  ¥œŒ"
  #define TXT_PODSVIETENIE   "Øœ∆“ƒ«”À¬"
  #define TXT_MIN   "¨ Œ"
  #define TXT_MAX   "¨¬À“"
  #define TXT_VALCE   "™œÃ-ƒœ ◊ Ã Œ∆—œƒ"
  #define TXT_VSTREKOVAC   "£–—⁄“À"
  #define TXT_KOLESA   "∞¬…Õ«— Ÿ Œ"
  #define TXT_CIDLO   "•¬”ÿ À “Àœ—œ“” "
  #define TXT_NAKLON   "™—«Œ"
  #define TXT_POCETMENUBC   "ÂÊ ‹À—¬Œ¬ √À"
  #define TXT_MAX_DOBA   "Æ”∆⁄÷"
  #define TXT_OBR_ZRYCHLENIE    "ªÀ—. ‘“Àœ—«Œ ›"
  #define TXT_OBR_PRETAZENIE    "ªÀ—. –«—«≈—‘…œÀ G"
  #define TXT_OBR_MOTOR    "ªÀ—. ∆ƒ ≈¬”«Ã›"
  #define TXT_OBR_SPRINT   "ªÀ—.–—œ÷œ»∆.∆ “”."
  #define TXT_OFF   "£⁄À"
  #define TXT_ON   "£ÀÃ"
  #define TXT_WELCOMETEXT   "Ø— ƒ«”“”ƒ «"
  #define TXT_NAST_NADRZE   "≥—œƒ. ”œ–Ã."
  #define TXT_OUT   "≤ƒœ…∆"
  #define TXT_J   "°"
  #define TXT_C   "N"
  #define TXT_CAS   "£—«Õ›"
  #define TXT_ZRYCHLENIE     "≥“Àœ—«Œ « “ 0 ∆œ"
  #define TXT_OTACKY   "Æ√/Õ Œ"
  #define TXT_DLZKA_VSTREKU   "£—«Õ› ƒ–—⁄“À¬"
  #define TXT_400M   "£—«Õ› –—œ÷œ»∆."
  #define TXT_RYCHLOST   "±Àœ—œ“”€:"
  #define TXT_TOT   "£“«≈œ"
  #define TXT_TEPLOTA_MOTORU   "≤«Õ–. Õ¬“Ã¬"


  #define TXT_WWW2   ""
  #define TXT_KMH   "ÀÕ/ÿ"
  #define TXT_l100Km   "Ã/100ÀÕ"
  #define TXT_KM   "ÀÕ"
  #define TXT_KMHR   "ÀÕ"
  #define TXT_KMSR   "/ÿ"
  #define TXT_L100KMHR   "Ã/"
  #define TXT_L100KMSR   "100"
  #define TXT_WWW   "   www.ppf.borec.cz"
  #define TXT_H   "ÿ"
  #define TXT_M   "Õ"
  #define TXT_S   "ƒ"
  #define TXT_V   "ƒ"
 	#define TXT_L		"Ã"

#endif





#ifdef S65_LANG_SP


  #define TXT_HODINY   "Reloj"
  #define TXT_CENA   "Precios"
  #define TXT_SERVIS_Z   "Servicio sigue"
  #define TXT_SERVIS_I   "Servicio int."
  #define TXT_FARBY   "Color"
  #define TXT_TEXT   "Text"
  #define TXT_PODKLAD   "Fondo"
  #define TXT_PODSVIETENIE   "Iluminacion"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "ÂÊ de cilindros"
  #define TXT_VSTREKOVAC   "Inyector"
  #define TXT_KOLESA   "Neumaticos"
  #define TXT_CIDLO   "Sensor de veloci."
  #define TXT_NAKLON   "Cero de inclinacion"
  #define TXT_POCETMENUBC   "ÂÊ de pantallas"
  #define TXT_MAX_DOBA   "Parada de segurid."
  #define TXT_OBR_ZRYCHLENIE    "Aceleracion panta."
  #define TXT_OBR_PRETAZENIE    "G pantalla"
  #define TXT_OBR_MOTOR    "Motor pantalla"
  #define TXT_OBR_SPRINT   "Sprint pantalla"
  #define TXT_OFF   "OFF"
  #define TXT_ON   " ON"
  #define TXT_WELCOMETEXT   "Bien. texto"
  #define TXT_NAST_NADRZE   "Nivel comb."
  #define TXT_OUT   "Ext"
  #define TXT_J   "A"
  #define TXT_C   "G"
  #define TXT_CAS   "Tiem:"
  #define TXT_ZRYCHLENIE     "Aceleracion 0 a"
  #define TXT_OTACKY   "RPM"
  #define TXT_DLZKA_VSTREKU   "Inyector tiempo"
  #define TXT_400M   "Sprint"
  #define TXT_RYCHLOST   "Velocidad:"
  #define TXT_TOT   "Sum"
	#define TXT_TEPLOTA_MOTORU "Aceite temp.  "

 	#define TXT_WWW2   ""
  #define TXT_KMH   "Km/h"
  #define TXT_l100Km   "l/100Km"
  #define TXT_KM   "Km"
  #define TXT_KMHR   "Km"
  #define TXT_KMSR   "/h"
  #define TXT_L100KMHR   "l/"
  #define TXT_L100KMSR   "100"
  #define TXT_WWW   "   www.ppf.borec.cz"
  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
 	#define TXT_L		"l"



#endif



#ifdef S65_LANG_BU


	#define AZBUKA


  #define TXT_HODINY   "∑¬“œƒŒ À"
  #define TXT_CENA   "∂«Œ¬ Œ¬ ≈œ— ƒœ"
  #define TXT_SERVIS_Z   "±«—ƒ … “Ã«∆"
  #define TXT_SERVIS_I   "±«—ƒ … –—«…"
  #define TXT_FARBY   "∂ƒ«”œƒ«"
  #define TXT_TEXT   "≤«À“”"
  #define TXT_PODKLAD   "  ¥œŒ"
  #define TXT_PODSVIETENIE   "Æ“ƒ«”›ƒ¬Œ«"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "¢—œ‡ ◊ Ã Œ∆— "
  #define TXT_VSTREKOVAC   "©Œ»«À”œ—"
  #define TXT_KOLESA   "∞¬…Õ«—-≈‘Õ "
  #define TXT_CIDLO   "±«Œ…œ— …¬ “Àœ—œ“”"
  #define TXT_NAKLON   "µœ— …œŒ” —. Œ¬ ¬ƒ”œÕ."
  #define TXT_POCETMENUBC   "≠œÕ«— Œ¬ BC «À—¬Œ"
  #define TXT_MAX_DOBA   "∏œ’ —.√«… –œÿ ƒÀ¬"
  #define TXT_OBR_ZRYCHLENIE    "¶À—¬Œ ‘“Àœ—«Œ «"
  #define TXT_OBR_PRETAZENIE    "¶À—¬Œ G"
  #define TXT_OBR_MOTOR    "¶À—¬Œ ∆ƒ ≈¬”«Ã"
  #define TXT_OBR_SPRINT   "¶À—.“Àœ—.œ”“«ÿÀ¬"
  #define TXT_OFF   "OFF"
  #define TXT_ON   " ON"
  #define TXT_WELCOMETEXT   "Øœ…∆—¬ƒ"
  #define TXT_NAST_NADRZE   "§œ— ƒœÕ«—"
  #define TXT_OUT   "£‚Œ"
  #define TXT_J   "°"
  #define TXT_C   "N"
  #define TXT_CAS   "£—«Õ«"
  #define TXT_ZRYCHLENIE     "≥“Àœ—«Œ « œ” 0 ∆œ"
  #define TXT_OTACKY   "Æ√œ—œ” "
  #define TXT_DLZKA_VSTREKU   "© Œ»«À”œ—-ƒ—«Õ«"
  #define TXT_400M   "®¬“ ÿ¬Œ«-ƒ—«Õ«"
  #define TXT_RYCHLOST   "±Àœ—œ“”"
  #define TXT_TOT   "£“."
  #define TXT_TEPLOTA_MOTORU   "≤«Õ–. Õ¬“Ãœ”œ"

 #define TXT_WWW2   ""
  #define TXT_KMH   "ÀÕ/ÿ"
  #define TXT_l100Km   "Ã/100ÀÕ"
  #define TXT_KM   "ÀÕ"
  #define TXT_KMHR   "ÀÕ"
  #define TXT_KMSR   "/ÿ"
  #define TXT_L100KMHR   "Ã/"
  #define TXT_L100KMSR   "100"
  #define TXT_WWW   "   www.ppf.borec.cz"
  #define TXT_H   "ÿ"
  #define TXT_M   "Õ"
  #define TXT_S   "ƒ"
  #define TXT_V   "ƒ"
 	#define TXT_L		"Ã"

#endif



#ifdef S65_LANG_FR


  #define TXT_HODINY   "Heure"
  #define TXT_CENA   "Prix carburant"
  #define TXT_SERVIS_Z   "Revision"
  #define TXT_SERVIS_I   "Vidange"
  #define TXT_FARBY   "Couleur"
  #define TXT_TEXT   "Text"
  #define TXT_PODKLAD   "Bckgrd"
  #define TXT_PODSVIETENIE   "Eclairage"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "Nbre cylindres"
  #define TXT_VSTREKOVAC   "Injecteurs"
  #define TXT_KOLESA   "Pneus"
  #define TXT_CIDLO   "Indice vitesse"
  #define TXT_NAKLON   "La mise en platitude"
  #define TXT_POCETMENUBC   "Nombre d'ecrans"
  #define TXT_MAX_DOBA   "Pause"
  #define TXT_OBR_ZRYCHLENIE    "Ecr Acceleration"
  #define TXT_OBR_PRETAZENIE    "Force"
  #define TXT_OBR_MOTOR    "Ecran moteur"
  #define TXT_OBR_SPRINT   "Ecran sprint"
  #define TXT_OFF   "OFF"
  #define TXT_ON   " ON"
  #define TXT_WELCOMETEXT   "Txt accueil"
  #define TXT_NAST_NADRZE   "Niveau carb"
  #define TXT_OUT   "Ext"
  #define TXT_J   "A"
  #define TXT_C   "B"
  #define TXT_CAS   "Temps"
  #define TXT_ZRYCHLENIE     "Acceleration 0 a"
  #define TXT_OTACKY   "Trs/min"
  #define TXT_DLZKA_VSTREKU   "Injecteurs"
  #define TXT_400M   "Chronometre"
  #define TXT_RYCHLOST   "Vitesse"
  #define TXT_TOT   "Tot"
  #define TXT_TEPLOTA_MOTORU   "TempÄ huile"
  #define TXT_INT   "INT"
  #define TXT_LAP   "LAP"
  #define TXT_STOPKY   "Chronometre"
  #define TXT_OBR_STOPKY   "Ecran chronometre"
  #define TXT_OBR_DEVELOP   "Ecran develop"
  #define TXT_LAMBDA   "Lamda"
  #define TXT_LAMBDA_M   "Mesures Lambda"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"




 	#define TXT_WWW2   ""
// 	#define TXT_WWW2   "  calibra-concept.net"
  #define TXT_KMH   "Km/h"
  #define TXT_l100Km   "l/100Km"
  #define TXT_KM   "Km"
  #define TXT_KMHR   "Km"
  #define TXT_KMSR   "/h"
  #define TXT_L100KMHR   "l/"
  #define TXT_L100KMSR   "100"
  #define TXT_WWW   "   www.ppf.borec.cz"
  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
 	#define TXT_L		"l"


#endif


#ifdef S65_LANG_EST

  #define TXT_HODINY   "Kellaaeg"
  #define TXT_CENA   "Kytte hind"
  #define TXT_SERVIS_Z   "Hoolduseni km"
  #define TXT_SERVIS_I   "Hoolduse interv"
  #define TXT_FARBY   "Varvid"
  #define TXT_TEXT   "Text"
  #define TXT_PODKLAD   "Taust"
  #define TXT_PODSVIETENIE   "Valgustus"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "Silindrite arv"
  #define TXT_VSTREKOVAC   "Pihusti"
  #define TXT_KOLESA   "Rehvid"
  #define TXT_CIDLO   "Kiirus impulsid"
  #define TXT_NAKLON   "Korrektsioon"
  #define TXT_POCETMENUBC   "BC lk. nr."
  #define TXT_MAX_DOBA   "Puhkepaus"
  #define TXT_OBR_ZRYCHLENIE    "Kiirendus seaded"
  #define TXT_OBR_PRETAZENIE    "G seaded"
  #define TXT_OBR_MOTOR    "Mootori seaded"
  #define TXT_OBR_SPRINT   "Sprint seaded"
  #define TXT_OFF   "OFF"
  #define TXT_ON   "ON"
  #define TXT_WELCOMETEXT   "Tervit.text"
  #define TXT_NAST_NADRZE   "Kytte tase"
  #define TXT_OUT   "Out"
  #define TXT_J   "A"
  #define TXT_C   "O"
  #define TXT_CAS   "Aeg"
  #define TXT_ZRYCHLENIE     "Kiirendus 0 kuni"
  #define TXT_OTACKY   "RPM"
  #define TXT_DLZKA_VSTREKU   "Pihusti aeg"
  #define TXT_400M   "Tulemused"
  #define TXT_RYCHLOST   "Kiirus  "
  #define TXT_TOT   "Tot"
  #define TXT_TEPLOTA_MOTORU   "Oli temp."




  #define TXT_WWW2   ""
  #define TXT_KMH   "Km/h"
  #define TXT_l100Km   "l/100Km"
  #define TXT_KM   "Km"
  #define TXT_KMHR   "Km"
  #define TXT_KMSR   "/h"
  #define TXT_L100KMHR   "l/"
  #define TXT_L100KMSR   "100"
  #define TXT_WWW   "   www.ppf.borec.cz"
  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
  #define TXT_L   "l"

#endif

#ifdef S65_LANG_PORT

 	#define TXT_HODINY   "Relogio"
  #define TXT_CENA   "Preco Combust."
  #define TXT_SERVIS_Z   "Proxima revisao"
  #define TXT_SERVIS_I   "Mudanca de oleo"
  #define TXT_FARBY   "Cores"
  #define TXT_TEXT   "Texto"
  #define TXT_PODKLAD   " Fundo"
  #define TXT_PODSVIETENIE   "Iluminacao"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "ÂÊ de cilindros"
  #define TXT_VSTREKOVAC   "Injetores"
  #define TXT_KOLESA   "Pneus"
  #define TXT_CIDLO   "Sensor velocidade"
  #define TXT_NAKLON   "Inclinacao"
  #define TXT_POCETMENUBC   "ÂÊ da tela do BC"
  #define TXT_MAX_DOBA   "Paragem Seguranca"
  #define TXT_OBR_ZRYCHLENIE    "Tela de Aceleracao"
  #define TXT_OBR_PRETAZENIE    "Forca G"
  #define TXT_OBR_MOTOR    "Tela Motor"
  #define TXT_OBR_SPRINT   "Tela sprint"
  #define TXT_OFF   "Des"
  #define TXT_ON   "Lig"
  #define TXT_WELCOMETEXT   "Bem vindo"
  #define TXT_NAST_NADRZE   "Nivel Comb."
  #define TXT_OUT   "Fora"
  #define TXT_J   "A"
  #define TXT_C   "O"
  #define TXT_CAS   "Tempo"
  #define TXT_ZRYCHLENIE     "Aceleracao 0 aos"
  #define TXT_OTACKY   "RPM"
  #define TXT_DLZKA_VSTREKU   "Tempo Injetor"
  #define TXT_400M   "Tempo distancia"
  #define TXT_RYCHLOST   "Velocidade"
  #define TXT_TOT   "Tot"
  #define TXT_TEPLOTA_MOTORU   "Temp. do oleo"
	#define TXT_OBR_STOPKY 		"Ecran cronometro"
	#define TXT_STOPKY		 		"Cronometro"
	#define TXT_INT						"INT"
	#define TXT_LAP						"LAP"
  #define TXT_OBR_DEVELOP   "Ecran diagnostico"
	#define TXT_LAMBDA	 			"Lambda"
	#define TXT_LAMBDA_M 			"Lambda medicao"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"





  #define TXT_WWW2   ""
  #define TXT_KMH   "Km/h"
  #define TXT_l100Km   "l/100Km"
  #define TXT_KM   "Km"
  #define TXT_KMHR   "Km"
  #define TXT_KMSR   "/h"
  #define TXT_L100KMHR   "l/"
  #define TXT_L100KMSR   "100"
  #define TXT_WWW   "   www.ppf.borec.cz"
  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
  #define TXT_L   "l"

#endif




#ifdef S65_LANG_AUS

	#define LCD_MIRROR
	#define	H12

	#define TXT_HODINY				"Clock"
	#define TXT_CENA			  	"Fuel price"
  #define TXT_0Kc				  	"0Kc"
	#define TXT_SERVIS_Z	  	"Service left"
	#define TXT_SERVIS_I	  	"Service int."
	#define TXT_FARBY			  	"Colours"
	#define TXT_TEXT			  	"Text"
	#define TXT_PODKLAD		  	"Bckgrnd"
	#define TXT_PODSVIETENIE "Illumination"
	#define TXT_MIN				 		"Min"
	#define TXT_MAX				 		"Max"
	#define TXT_VALCE					"Nr. of cylinders"
	#define TXT_VSTREKOVAC		"Injector"
	#define TXT_KOLESA				"Tyres"
	#define TXT_CIDLO					"Speed sensor"
	#define TXT_NAKLON				"Heeling"
	#define TXT_CAS				  	"Time:"
	#define TXT_ZRYCHLENIE  	"Acceleration 0 to"
	#define TXT_POCETMENUBC		"Nr. of BC screen"	
	#define TXT_MAX_DOBA			"Safety break"
	#define TXT_OTACKY				"RPM"
	#define TXT_DLZKA_VSTREKU	"Injector time"
	#define TXT_OBR_ZRYCHLENIE "Scr.acceleration"
	#define TXT_OBR_PRETAZENIE "Scr. G"
	#define TXT_OBR_MOTOR 		"Scr.engine"
	#define TXT_OBR_STOPKY 		"Scr.stop watch"
	#define TXT_OBR_DEVELOP		"Scr.develop"
	#define TXT_STOPKY		 		"Stop watch"
	#define TXT_INT						"INT"
	#define TXT_LAP						"LAP"
	#define TXT_OFF						"OFF"
	#define TXT_ON						" ON"
	#define TXT_J							"A"
	#define TXT_C							"O"
	#define TXT_WWW						"   www.ppf.borec.cz"
	#define TXT_WWW2					" "
	#define TXT_H							"h"
	#define TXT_M							"m"
	#define TXT_S							"s"
	#define TXT_TOT						"Tot"
	#define TXT_V							"V"
	#define TXT_OUT						"Out"
	#define TXT_WELCOMETEXT		"Welcome txt"
	#define TXT_NAST_NADRZE		"Fuel level"
	#define TXT_400M					"Measuring time"
	#define TXT_OBR_SPRINT		"Scr. sprint"
	#define TXT_RYCHLOST			"Speed:"
	#define TXT_TEPLOTA_MOTORU "Oil temp.     "
	#define TXT_LAMBDA	 			"Lambda"
	#define TXT_LAMBDA_M 			"Lambda measurement"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"


	#define TXT_KMH						"Km/h"
	#define TXT_l100Km				"l/100Km"
	#define TXT_KM						"Km"
	#define TXT_KMHR					"Km"
	#define TXT_KMSR					"/h"
	#define TXT_L100KMHR			"l/"
	#define TXT_L100KMSR			"100"
 	#define TXT_L		"l"

  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
  #define TXT_L   "l"
#endif


#ifdef S65_LANG_NL



  #define TXT_HODINY   "Klok"
  #define TXT_CENA   "Benzine Prijs"
  #define TXT_SERVIS_Z   "Auto Onderhoud"
  #define TXT_SERVIS_I   "Onderhoud int."
  #define TXT_FARBY   "Kleuren"
  #define TXT_TEXT   "Text"
  #define TXT_PODKLAD   "Agrnd"
  #define TXT_PODSVIETENIE   "Verlichting"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "Aantal Cilinders"
  #define TXT_VSTREKOVAC   "Injector"
  #define TXT_KOLESA   "Banden"
  #define TXT_CIDLO   "Snelheids Sensor"
  #define TXT_NAKLON   "Benz Tank Reset"
  #define TXT_POCETMENUBC   "Nr. BC Scherm"
  #define TXT_MAX_DOBA   "Rust Tijd"
  #define TXT_OBR_ZRYCHLENIE    "Sch. Acceleratie"
  #define TXT_OBR_PRETAZENIE    "Sch. G krachten"
  #define TXT_OBR_MOTOR    "Sch. Motor"
  #define TXT_OBR_SPRINT   "Sch. Sprint"
  #define TXT_OFF   "UIT"
  #define TXT_ON   "AAN"
  #define TXT_WELCOMETEXT   "Welkom txt"
  #define TXT_NAST_NADRZE   "Brandstof"
  #define TXT_OUT   "Tmp"
  #define TXT_J   "A"
  #define TXT_C   "O"
  #define TXT_CAS   "Tijd"
  #define TXT_ZRYCHLENIE     "Acceleratie 0 tot"
  #define TXT_OTACKY   "RPM"
  #define TXT_DLZKA_VSTREKU   "Injector tijd"
  #define TXT_400M   "Meettijden"
  #define TXT_RYCHLOST   "Snelheid"
  #define TXT_TOT   "Tot"
  #define TXT_TEPLOTA_MOTORU   "Olie temp."
  #define TXT_INT   "INT"
  #define TXT_LAP   "LAP"
  #define TXT_STOPKY   "Stop watch"
  #define TXT_OBR_STOPKY   "Sch.stop watch"
  #define TXT_OBR_DEVELOP   "Sch.BC diagnose"
  #define TXT_LAMBDA   "Lambda"
  #define TXT_LAMBDA_M   "Lambda meting"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"




	#define TXT_WWW						"   www.ppf.borec.cz"
	#define TXT_WWW2					" "
	#define TXT_KMH						"Km/h"
	#define TXT_l100Km				"l/100Km"
	#define TXT_KM						"Km"
	#define TXT_KMHR					"Km"
	#define TXT_KMSR					"/h"
	#define TXT_L100KMHR			"l/"
	#define TXT_L100KMSR			"100"
 	#define TXT_L		"l"
  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
  #define TXT_L   "l"


#endif



#ifdef S65_LANG_FIN


  #define TXT_HODINY   "Kello"
  #define TXT_CENA   "Bensan hinta"
  #define TXT_SERVIS_Z   "Matkaa huoltoon"
  #define TXT_SERVIS_I   "Huoltovali"
  #define TXT_FARBY   "Varit"
  #define TXT_TEXT   "Text"
  #define TXT_PODKLAD   "Tausta"
  #define TXT_PODSVIETENIE   "Valaistus"
  #define TXT_MIN   "Min"
  #define TXT_MAX   "Max"
  #define TXT_VALCE   "Sylinterien maara"
  #define TXT_VSTREKOVAC   "Suutin"
  #define TXT_KOLESA   "Renkaat"
  #define TXT_CIDLO   "Nopeusanturi"
  #define TXT_NAKLON   "Tasaus"
  #define TXT_POCETMENUBC   "BC nayttojen maara"
  #define TXT_MAX_DOBA   "Taukovali"
  #define TXT_OBR_ZRYCHLENIE    "Kiihtyvyysnaytto"
  #define TXT_OBR_PRETAZENIE    "G-Voimien naytto"
  #define TXT_OBR_MOTOR    "Moottorinaytto"
  #define TXT_OBR_SPRINT   "Kiihdytysnaytto"
  #define TXT_OFF   "OFF"
  #define TXT_ON   " ON"
  #define TXT_WELCOMETEXT   "Aloitus txt"
  #define TXT_NAST_NADRZE   "Bens. Taso"
  #define TXT_OUT   "Ulk"
  #define TXT_J   "N"
  #define TXT_C   "Y"
  #define TXT_CAS   "Aika:"
  #define TXT_ZRYCHLENIE     "Kiihtyvyys 0  -"
  #define TXT_OTACKY   "RPM"
  #define TXT_DLZKA_VSTREKU   "Suut. Aukiolo"
  #define TXT_400M   "Ajan mittaus"
  #define TXT_RYCHLOST   "Nopeus:"
  #define TXT_TOT   "Yht"
  #define TXT_TEPLOTA_MOTORU   "Oljyn lampo"
  #define TXT_INT   "INT"
  #define TXT_LAP   "LAP"
  #define TXT_STOPKY   "Ajastin"
  #define TXT_OBR_STOPKY   "Ajastin naytto"
  #define TXT_OBR_DEVELOP   "Kehittajan naytto"
  #define TXT_LAMBDA   "Lambda"
  #define TXT_LAMBDA_M   "Lambdan mittaus"
	#define TXT_BUFFER				"NBB"
	#define TXT_5V						" 5V"
	#define TXT_NB						" NB"
	#define TXT_WB						" WB"




	#define TXT_WWW						"   www.ppf.borec.cz"
	#define TXT_WWW2					" "
	#define TXT_KMH						"Km/h"
	#define TXT_l100Km				"l/100Km"
	#define TXT_KM						"Km"
	#define TXT_KMHR					"Km"
	#define TXT_KMSR					"/h"
	#define TXT_L100KMHR			"l/"
	#define TXT_L100KMSR			"100"
 	#define TXT_L		"l"
  #define TXT_H   "h"
  #define TXT_M   "m"
  #define TXT_S   "s"
  #define TXT_V   "V"
  #define TXT_L   "l"


#endif



#endif
